### ISSUE TITLE
Automation Script Variables and Launch Point Variables Configuraitons fail to deploy

### ISSUE THREAD

**Issue by jaredschrag** [sharptree/vscode-autoscript-deploy#16] opened 2024-05-13 17:13 UTC
There is a bug with deploying Automation Scripts to Maximo that have Script Variables defined as well as Launch Point Variables defined. To reproduce, create and Automation Script with Script Variables defined in Maximo. Then, using the extension, extract the Automation Script into the VSCode workspace. Note that the `scriptConfig` variable includes definitions for the Script Varibales that includes properties such as `noValidation` or `noAccessCheck` or `noAction` - these properties will cause errors if the extracted script is attempted to be deployed to Maximo. The error seems to indicate that these are read-only fields and cannot be changed.

Even if I remove these properties, and proceed to define Launch Point variables that override the defined Script Variables, deploying these configurations will error indicating that the Varibale Binding Value is a primary key or read-only.

In all cases, when the deployment fails for any of these issues, the result is that the script is deployed without any Script Variables and without any Launch Point variables (i.e. the deployment will delete the previously configured Script Varibbles and Launch Point Varibales).

**Comment by jvenhuizen** [comment] 2024-05-17 18:24
Thank you for your detailed report, I'll look into it and hopefully will have a fix published soon.

**Comment by jvenhuizen** [comment] 2024-05-22 17:47
I have been unable to reproduce this error.  Below is the script I was testing with, can you confirm that the error occurs with this script or can you provide a script that is failing?

`def main():
    if request is not None:
        return "A test value"

responseBody = main()

scriptConfig="""{
    "autoscript": "VARTEST",
    "description": "Variable Test",
    "version": "",
    "active": true,
    "logLevel": "ERROR",
    "autoScriptVars": [
        {
            "varname": "testvar",
            "description": "Variable test",
            "varBindingType": "ATTRIBUTE",
            "varType": "OUT",
            "allowOverride": true,
            "noValidation": false,
            "noAccessCheck": true,
            "noAction": true
        }
    ],
    "scriptLaunchPoints": [
        {
            "launchPointName": "VARTEST",
            "launchPointType": "OBJECT",
            "active": true,
            "description": "Variable test",
            "objectName": "ASSET",
            "save": true,
            "add": true,
            "update": false,
            "delete": false,
            "afterCommit": true,
            "launchPointVars": [
                {
                    "varName": "testvar",
                    "varBindingValue": "ASSETNUM"
                }
            ]
        }
    ]
}"""`

**Comment by jaredschrag** [comment] 2024-05-23 18:49
This test script "VARTEST" seems to work without error when deploying and extracting via the VSCode Extension. However, I did notice that when I started to use the extension, it deployed updated SHARPTREE automation scripts (updating from 1.28.0 to 1.29.0). Perhaps some change in 1.29.0 has resolved that issue?

I've also tested with one of our own scripts configured with Script Variables/Launch Point Variables - and that deploy/extract worked as well. Next, I'll test using the companion NPM package to deploy script changes and see if that works without error.

**Comment by jaredschrag** [comment] 2024-05-23 19:34
I can confirm that the VARTEST script above does work without any errors! However, I still see the issue with one of our own automation scripts and the difference I see between that script and your test script here is all of our Script Variables binding types are "LITERAL" and the Script Variable Type is "IN" in the script that fails. If I take your example above and tweak the Script Variable binding type to be "LITERAL" and the Script variable type to be "IN", it will reproduce the issue:

```
def main():
    if request is not None:
        return "A test value"


responseBody = main()

scriptConfig = """{
  "autoscript": "VARTEST",
  "description": "Variable Test",
  "version": "",
  "active": true,
  "logLevel": "ERROR",
  "autoScriptVars": [
    {
      "varname": "testvar",
      "description": "Literal Variable test",
      "varBindingType": "LITERAL",
      "varType": "IN",
      "allowOverride": true,
      "noValidation": false,
      "noAccessCheck": false,
      "noAction": false,
      "literalDataType": "ALN",
      "varBindingValue": "1"
    }
  ],
  "scriptLaunchPoints": [
    {
      "launchPointName": "VARTEST",
      "launchPointType": "OBJECT",
      "active": true,
      "description": "Variable test",
      "objectName": "ASSET",
      "save": true,
      "add": true,
      "update": false,
      "delete": false,
      "afterCommit": true,
      "launchPointVars": [
        {
          "varName": "testvar",
          "varBindingValue": "0"
        }
      ]
    }
  ]
}
"""
```

**Comment by jaredschrag** [comment] 2024-05-23 20:09
I suspect strongly that the issue is that my binding type LITERAL Script Varibales are specified as varibale type "IN"; within the `deployScript` function, when it goes to fill in the newly created SriptVariable field values, when the VARTYPE attribute is set (to "IN"), the base maximo code makes the noValidation, noAccessCheck, and noAction fields become read-only. Then the `deployScript` function continues and attempts to set these noValidation, noAccessCheck, and noAction field values (even though they are readonly at this point). It seams to me that either:
1. The underlying `mbo.setValue(...)` logic could be changed to use NOACCESSCHECK; or,
2. The setting of the `autoscriptVar` attaributes become dynamic depending on the value set for the VARTYPE attribute. For eaxmple, if the VARTYPE was set to "IN" then there is no attempt to set the NOVALIDATION, NOACCESSCHECK, and NOACTION attributes (because the base code will have made them readonly due to VARTYPE being set to "IN").

**Comment by jvenhuizen** [comment] 2024-05-23 21:38
I have published an update, 1.13.8, that should address this issue.

**Comment by jaredschrag** [comment] 2024-05-24 15:44
Version 1.13.8 is a good advancement on this issue! Scripts are deploying without error, it seems. However, I think there are still issues deploying the Launch Point Script Variable overrides. The test script below illustrates the issue. 

I strongly suspect that when the `deployScript` function goes to set the Launch Point Variables (in the LAUNCHPOINTVARS MboSet), it is assume Maximo will auto-populate the set with default Mbos); however, it looks like it does not do this with Script Variables that are not of Binding Type "ATTRIBUTE". This test script will illustrate the issue - it has Script Variables of every possible Binding Type (ATTRIBUTE, LITERAL, MAXVAR, and SYSPROP) and the Launch Point overrides every Script Variable value. When this script deploys, there is no error; however, it does not add or update any found Mbos for the overrides except for the override for the Script Variable with Binding Type of "ATTRIBUTE".

```
def main():
    if request is not None:
        return "A test value"


responseBody = main()


scriptConfig="""{
    "autoscript": "VARTEST",
    "description": "Variable Test",
    "version": "",
    "active": true,
    "logLevel": "ERROR",
    "autoScriptVars": [
        {
            "varname": "testvar1",
            "description": "Literal Variable test",
            "varBindingType": "LITERAL",
            "varType": "IN",
            "allowOverride": true,
            "noValidation": false,
            "noAccessCheck": false,
            "noAction": false,
            "literalDataType": "ALN",
            "varBindingValue": "1"
        },
        {
            "varname": "testvar2",
            "description": "Attribute Variable test",
            "varBindingType": "ATTRIBUTE",
            "varType": "INOUT",
            "allowOverride": true,
            "noValidation": false,
            "noAccessCheck": false,
            "noAction": false
        },
        {
            "varname": "testvar3",
            "description": "MaxVar Variable test",
            "varBindingType": "MAXVAR",
            "varType": "IN",
            "allowOverride": true,
            "noValidation": false,
            "noAccessCheck": false,
            "noAction": false,
            "varBindingValue": "ALLOWSPORDER"
        },
        {
            "varname": "testvar4",
            "description": "SysProp Variable test",
            "varBindingType": "SYSPROP",
            "varType": "IN",
            "allowOverride": true,
            "noValidation": false,
            "noAccessCheck": false,
            "noAction": false,
            "varBindingValue": "mxe.crontask.donotrun"
        }
    ],
    "scriptLaunchPoints": [
        {
            "launchPointName": "VARTEST",
            "launchPointType": "OBJECT",
            "active": true,
            "description": "Variable test",
            "objectName": "ASSET",
            "save": true,
            "add": true,
            "update": false,
            "delete": false,
            "afterCommit": true,
            "launchPointVars": [
                {
                    "varName": "testvar1",
                    "varBindingValue": "0"
                },
                {
                    "varName": "testvar2",
                    "varBindingValue": "DESCRIPTION_LONGDESCRIPTION"
                },
                {
                    "varName": "testvar3",
                    "varBindingValue": "ALLUSERGROUP"
                },
                {
                    "varName": "testvar4",
                    "varBindingValue": "mxe.crontask.dorun"
                }
            ]
        }
    ]
}"""
```

**Comment by jvenhuizen** [comment] 2024-05-24 18:06
Thank you for the example, I have updated and pushed a fix for this, which should be out in a few minutes (1.13.9). Once you have confirmed the fix I will update the npm package as well to match.

**Comment by jaredschrag** [comment] 2024-05-24 20:59
It appears that this fix is working! Please proceed with the NPM pkg update as well. Thank you for the quick turnaround on this issue!

**Comment by jvenhuizen** [comment] 2024-05-24 21:06
I have updated the NPM tools with the same scripts.

**Closed as completed by jvenhuizen** 2024-05-24 21:06 UTC
